name: Release NuGet Package

on:
  push:
    tags:
      - 'v*'           # Triggers on tags like v1.0.0, v2.1.3 etc.

jobs:
  build-pack-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
            8.0.x

      - name: Restore dependencies
        run: dotnet restore Registrar.sln

      - name: Build (Core only)
        run: dotnet build Registrar/Registrar.csproj --configuration Release --no-restore

      - name: Pack (Core only)
        run: dotnet pack Registrar/Registrar.csproj --configuration Release --no-build --output ./nupkg

      - name: Publish to NuGet.org
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Upload NuGet package to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./nupkg/*.nupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/TestResults/*.trx'
